package com.epam.esm.validator;

public enum ValidationError {
    TAG_NAME_REQUIRED,
    GIFT_CERTIFICATE_NAME_REQUIRED,
    GIFT_CERTIFICATE_DESCRIPTION_REQUIRED,
    GIFT_CERTIFICATE_PRICE_REQUIRED,
    GIFT_CERTIFICATE_DURATION_REQUIRED,
    ORDER_USER_REQUIRED,
    ORDER_ITEMS_REQUIRED,

    IMPOSSIBLE_TO_UPDATE_SEVERAL_GIFT_CERTIFICATE_FIELDS,
    NO_GIFT_CERTIFICATE_FIELDS_TO_UPDATE,

    INVALID_ORDER_ITEMS_AMOUNT,
    NOT_UNIQUE_GIFT_CERTIFICATES_IN_ORDER,

    TOO_SHORT_GIFT_CERTIFICATE_DESCRIPTION,
    TOO_LONG_GIFT_CERTIFICATE_DESCRIPTION,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_DESCRIPTION,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_GIFT_CERTIFICATE_DESCRIPTION,

    TOO_SHORT_GIFT_CERTIFICATE_DURATION,
    TOO_LONG_GIFT_CERTIFICATE_DURATION,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_DURATION,

    TOO_SMALL_GIFT_CERTIFICATE_PRICE,
    TOO_BIG_GIFT_CERTIFICATE_PRICE,
    INVALID_GIFT_CERTIFICATE_PRICE_FORMAT,

    INVALID_TAGS_AMOUNT,
    NOT_UNIQUE_TAGS_IN_GIFT_CERTIFICATE,

    TOO_SHORT_TAG_NAME,
    TOO_LONG_TAG_NAME,
    INVALID_SYMBOLS_IN_TAG_NAME,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_TAG_NAME,

    TOO_SHORT_GIFT_CERTIFICATE_NAME,
    TOO_LONG_GIFT_CERTIFICATE_NAME,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_NAME,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_GIFT_CERTIFICATE_NAME,

    NOT_UNIQUE_USER_LOGIN,
    USER_LOGIN_REQUIRED,
    INVALID_USER_LOGIN,
    TOO_SHORT_USER_LOGIN,
    TOO_LONG_USER_LOGIN,

    USER_PASSWORD_REQUIRED,
    INVALID_USER_PASSWORD,
    TOO_SHORT_USER_PASSWORD,
    TOO_LONG_USER_PASSWORD,

    USER_NAME_REQUIRED,
    INVALID_USER_NAME,
    TOO_SHORT_USER_NAME,
    TOO_LONG_USER_NAME,

    USER_SURNAME_REQUIRED,
    INVALID_USER_SURNAME,
    TOO_SHORT_USER_SURNAME,
    TOO_LONG_USER_SURNAME,

    USER_EMAIL_REQUIRED,
    INVALID_USER_EMAIL,
    TOO_SHORT_USER_EMAIL,
    TOO_LONG_USER_EMAIL,

    INVALID_NAME_ORDERING_TYPE,
    INVALID_CREATE_DATE_ORDERING_TYPE,
    INVALID_ORDER_ORDERING_TYPE,

    INVALID_PAGE_NUMBER,
    TOO_SMALL_PAGE_NUMBER,

    INVALID_PAGE_SIZE,
    TOO_SMALL_PAGE_SIZE,
    TOO_BIG_PAGE_SIZE,

    PAGE_IS_OUT_OF_RANGE,
}
