package com.epam.esm.validator;

public enum ValidationError {
    TAG_NAME_REQUIRED,
    GIFT_CERTIFICATE_NAME_REQUIRED,
    GIFT_CERTIFICATE_DESCRIPTION_REQUIRED,
    GIFT_CERTIFICATE_PRICE_REQUIRED,
    GIFT_CERTIFICATE_DURATION_REQUIRED,

    TOO_SHORT_GIFT_CERTIFICATE_DESCRIPTION,
    TOO_LONG_GIFT_CERTIFICATE_DESCRIPTION,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_DESCRIPTION,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_GIFT_CERTIFICATE_DESCRIPTION,

    TOO_SHORT_GIFT_CERTIFICATE_DURATION,
    TOO_LONG_GIFT_CERTIFICATE_DURATION,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_DURATION,

    TOO_SMALL_GIFT_CERTIFICATE_PRICE,
    TOO_BIG_GIFT_CERTIFICATE_PRICE,
    INVALID_GIFT_CERTIFICATE_PRICE_FORMAT,

    TOO_SHORT_TAG_NAME,
    TOO_LONG_TAG_NAME,
    INVALID_SYMBOLS_IN_TAG_NAME,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_TAG_NAME,

    TOO_SHORT_GIFT_CERTIFICATE_NAME,
    TOO_LONG_GIFT_CERTIFICATE_NAME,
    INVALID_SYMBOLS_IN_GIFT_CERTIFICATE_NAME,
    INVALID_LEADING_OR_CLOSING_SYMBOLS_IN_GIFT_CERTIFICATE_NAME,

    INVALID_NAME_ORDERING_TYPE,
    INVALID_CREATE_DATE_ORDERING_TYPE
}
