/* +++ tags +++ */

create table tags
(
    id   bigserial
        constraint tags_pk
            primary key,
    name varchar(50)
);

alter table tags
    owner to postgres;

create unique index tags_name_uindex
    on tags (name);


/* +++ roles +++ */

create table roles
(
    id   smallserial
        constraint roles_pk
            primary key,
    name varchar(35)
);

alter table roles
    owner to postgres;

create unique index roles_name_uindex
    on roles (name);


/* +++ users +++ */

create table users
(
    id       bigint generated by default as identity (maxvalue 2147483647)
        constraint pk_users
            primary key,
    login    varchar(50)  not null
        constraint uc_users_login
            unique,
    name     varchar(45)  not null,
    surname  varchar(100) not null,
    email    varchar(255) not null,
    id_role  smallint
        constraint users_role_fk
            references roles,
    password varchar(64)
);

alter table users
    owner to postgres;


/* +++ refresh_tokens +++ */

create table refresh_tokens
(
    id              bigserial
        constraint refresh_tokens_pk
            primary key,
    token           varchar(255),
    expiration_date timestamp(3),
    id_user         bigint
        constraint table_name_user_fk
            references users
            on update cascade on delete cascade
);

alter table refresh_tokens
    owner to postgres;

create unique index refresh_tokens_token_uindex
    on refresh_tokens (token);


/* +++ gift_certificates +++ */

create table gift_certificates
(
    id               bigserial
        constraint gift_certificates_pk
            primary key,
    name             varchar(100),
    description      varchar(500),
    price            numeric(7, 2),
    duration         smallint,
    create_date      timestamp(3),
    last_update_date timestamp(3),
    available        boolean default true
);

alter table gift_certificates
    owner to postgres;

create unique index gift_certificates_name_uindex
    on gift_certificates (name);


/* +++ gift_certificates_tags +++ */

create table gift_certificates_tags
(
    id_gift_certificate bigint not null
        constraint gift_certificates_tags_certificate_fk
            references gift_certificates
            on update cascade on delete cascade,
    id_tag              bigint not null
        constraint gift_certificates_tags_tag_fk
            references tags
            on update cascade on delete cascade,
    id                  bigserial
        constraint gift_certificates_tags_pk
            primary key
);

alter table gift_certificates_tags
    owner to postgres;


/* +++ orders +++ */

create table orders
(
    id                bigserial
        constraint orders_pk
            primary key,
    create_order_time timestamp(3) not null,
    update_order_time timestamp(3) not null,
    id_user           bigint
        constraint orders_user_fk
            references users,
    new_column        integer
);

alter table orders
    owner to postgres;


/* +++ order_items +++ */

create table order_items
(
    id                  bigserial
        constraint order_items_pk
            primary key,
    price               numeric(7, 2),
    id_gift_certificate bigint
        constraint order_items_certificate_fk
            references gift_certificates
            on update cascade on delete cascade,
    new_column          integer,
    id_order            bigint
        constraint order_items_order_fk
            references orders
            on update cascade on delete cascade
);

alter table order_items
    owner to postgres;