/* +++ tags +++ */

create table if not exists tags
(
    id   serial
        constraint tags_pk
            primary key,
    name varchar(50)
);

create unique index if not exists tags_name_uindex
    on tags (name);

create table if not exists roles
(
    id   serial
        constraint roles_pk
            primary key,
    name varchar(35)
);

create unique index if not exists roles_name_uindex
    on roles (name);


/* +++ users +++ */

create table if not exists users
(
    id       serial generated by default as identity
        constraint pk_users
            primary key,
    login    varchar(50)  not null
        constraint uc_users_login
            unique,
    name     varchar(45)  not null,
    surname  varchar(100) not null,
    email    varchar(255) not null,
    id_role  bigint
        constraint users_role_fk
            references roles,
    password varchar(64)
);

/* +++ refresh_tokens +++ */

create table if not exists refresh_tokens
(
    id              serial
        constraint refresh_tokens_pk
            primary key,
    token           varchar(255),
    expiration_date timestamp(3),
    id_user         bigint
        constraint table_name_user_fk
            references users
            on update cascade on delete cascade
);

create unique index if not exists refresh_tokens_token_uindex
    on refresh_tokens (token);


/* +++ gift_certificates +++ */

create table if not exists gift_certificates
(
    id               serial
        constraint gift_certificates_pk
            primary key,
    name             varchar(100),
    description      varchar(500),
    price            numeric(7, 2),
    duration         smallint,
    create_date      timestamp(3),
    last_update_date timestamp(3),
    available        boolean default true
);

create unique index if not exists gift_certificates_name_uindex
    on gift_certificates (name);


/* +++ gift_certificates_tags +++ */

create table if not exists gift_certificates_tags
(
    id_gift_certificate bigint not null
        constraint gift_certificates_tags_certificate_fk
            references gift_certificates
            on update cascade on delete cascade,
    id_tag              bigint not null
        constraint gift_certificates_tags_tag_fk
            references tags
            on update cascade on delete cascade,
    id                  serial
        constraint gift_certificates_tags_pk
            primary key
);


/* +++ orders +++ */

create table if not exists orders
(
    id                serial
        constraint orders_pk
            primary key,
    create_order_time timestamp(3) not null,
    update_order_time timestamp(3) not null,
    id_user           bigint
        constraint orders_user_fk
            references users,
    new_column        integer
);


/* +++ order_items +++ */

create table if not exists order_items
(
    id                  serial
        constraint order_items_pk
            primary key,
    price               numeric(7, 2),
    id_gift_certificate bigint
        constraint order_items_certificate_fk
            references gift_certificates
            on update cascade on delete cascade,
    new_column          integer,
    id_order            bigint
        constraint order_items_order_fk
            references orders
            on update cascade on delete cascade
);